
default_language_version:
        python: python3

repos:

  # - repo: https://github.com/omnilib/ufmt
  #   rev: v2.1.0
  #   hooks:
  #     - id: ufmt
  #       additional_dependencies:
  #         - black == 22.6.0
  #         - usort == 1.0.4

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln

  - repo: https://github.com/isidentical/teyit
    rev: 0.4.3
    hooks:
      - id: teyit
